<script src="{{
        URL::asset('themes/assets/libs/jquery/dist/jquery.min.js') }}"></script>
<script src="{{
        URL::asset('themes/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="{{
        URL::asset('themes/assets/js/sidebarmenu.js') }}"></script>
<script src="{{
        URL::asset('themes/assets/js/app.min.js') }}"></script>
<script src="{{
        URL::asset('themes/assets/libs/simplebar/dist/simplebar.js') }}"></script>
